version: 2

project_name: nats-metrics-tag-mapper

before:
  hooks:
    - go mod tidy
builds:
  - id: "linux"
    main: ./cmd/nats-metrics-tag-mapper/main.go
    binary: ./cmd/nats-metrics-tag-mapper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -extldflags '-static'
checksum:
  name_template: 'checksums-credentials.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  skip_upload: false
sboms:
  - id: artifacts
    artifacts: archive
  - id: source
    artifacts: source